//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFAttrLookupDR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFAttrLookupDR.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; has not been found for data reference..
        /// </summary>
        public static string ERR_AttributeHasNotBeenFound {
            get {
                return ResourceManager.GetString("ERR_AttributeHasNotBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute has not been set for &apos;{0}&apos; data reference..
        /// </summary>
        public static string ERR_AttributeHasNotBeenSet {
            get {
                return ResourceManager.GetString("ERR_AttributeHasNotBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; has not been found for lookup..
        /// </summary>
        public static string ERR_AttributeLookupHasNotBeenFound {
            get {
                return ResourceManager.GetString("ERR_AttributeLookupHasNotBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data reference for attribute &apos;{0}&apos; has not been configured.
        /// </summary>
        public static string ERR_DataReferenceNotConfigured {
            get {
                return ResourceManager.GetString("ERR_DataReferenceNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input values.
        /// </summary>
        public static string ERR_NoInputValues {
            get {
                return ResourceManager.GetString("ERR_NoInputValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source attribute must be an string type.
        /// </summary>
        public static string ERR_SourceAttributeMustBeStringType {
            get {
                return ResourceManager.GetString("ERR_SourceAttributeMustBeStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply changes: {0}.
        /// </summary>
        public static string ERR_UnableToApplyChanges {
            get {
                return ResourceManager.GetString("ERR_UnableToApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized configuration setting &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        public static string ERR_UnrecognizedConfigurationSetting {
            get {
                return ResourceManager.GetString("ERR_UnrecognizedConfigurationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized reference value &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        public static string ERR_UnrecognizedRefValue {
            get {
                return ResourceManager.GetString("ERR_UnrecognizedRefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TITLE_Error {
            get {
                return ResourceManager.GetString("TITLE_Error", resourceCulture);
            }
        }
    }
}
